name: JD Price Monitor

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 时间 1:00 运行（即北京时间 9:00）
  workflow_dispatch:      # 允许手动触发

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run price checker
        env:
          SCKEY: ${{ secrets.SCKEY }}
          SKU_ID: ${{ secrets.SKU_ID }}
          PRICE_THRESHOLD: ${{ secrets.PRICE_THRESHOLD }}
        run: python jd_monitor.py
